/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SystemRouteImport } from './routes/system'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugClaimsRouteImport } from './routes/debug.claims'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugClaimsRoute = DebugClaimsRouteImport.update({
  id: '/debug/claims',
  path: '/debug/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/system': typeof SystemRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/debug/claims': typeof DebugClaimsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/system': typeof SystemRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/debug/claims': typeof DebugClaimsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/system': typeof SystemRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/debug/claims': typeof DebugClaimsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/system'
    | '/usage'
    | '/users'
    | '/auth/login'
    | '/debug/claims'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/system'
    | '/usage'
    | '/users'
    | '/auth/login'
    | '/debug/claims'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/system'
    | '/usage'
    | '/users'
    | '/auth/login'
    | '/debug/claims'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SystemRoute: typeof SystemRoute
  UsageRoute: typeof UsageRoute
  UsersRoute: typeof UsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DebugClaimsRoute: typeof DebugClaimsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/claims': {
      id: '/debug/claims'
      path: '/debug/claims'
      fullPath: '/debug/claims'
      preLoaderRoute: typeof DebugClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  SystemRoute: SystemRoute,
  UsageRoute: UsageRoute,
  UsersRoute: UsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  DebugClaimsRoute: DebugClaimsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
