-- Users table stores application-level user accounts
-- These are linked to OIDC identities but managed by our application
CREATE TABLE IF NOT EXISTS users (
	id         TEXT PRIMARY KEY,           -- UUID generated by us
	oidc_iss   TEXT NOT NULL,              -- OIDC issuer (e.g., Clerk domain)
	oidc_sub   TEXT NOT NULL,              -- OIDC subject (unique per provider)
	email      TEXT NOT NULL,              -- User's email from OIDC
	name       TEXT NOT NULL DEFAULT '',   -- User's display name
	role       TEXT NOT NULL DEFAULT 'user', -- Application role: 'admin' or 'user'
	status     TEXT NOT NULL DEFAULT 'active', -- Account status: 'active', 'suspended', 'deleted'
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	UNIQUE(oidc_iss, oidc_sub)              -- One user record per OIDC identity
);

-- Index for looking up users by OIDC identity (used on every login)
CREATE INDEX IF NOT EXISTS idx_users_oidc ON users(oidc_iss, oidc_sub);

-- Index for looking up users by email (used for admin searches)
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
