package users

import "time"

// Role represents an application-level user role.
type Role string

const (
	RoleUser  Role = "user"  // Regular user with basic access
	RoleAdmin Role = "admin" // Administrator with full access
)

// Status represents the user account status.
type Status string

const (
	StatusActive    Status = "active"    // Active account
	StatusSuspended Status = "suspended" // Temporarily suspended
	StatusDeleted   Status = "deleted"   // Soft deleted
)

// User represents an application user.
type User struct {
	ID        string    // UUID generated by the application
	OIDCIss   string    // OIDC issuer (e.g., https://clerk.example.com)
	OIDCSub   string    // OIDC subject (unique identifier from provider)
	Email     string    // User's email address
	Name      string    // User's display name
	Role      Role      // Application role
	Status    Status    // Account status
	CreatedAt time.Time // When the user was first created
	UpdatedAt time.Time // Last update timestamp
}

// IsAdmin returns true if the user has the admin role.
func (u *User) IsAdmin() bool {
	return u.Role == RoleAdmin
}

// IsActive returns true if the user account is active.
func (u *User) IsActive() bool {
	return u.Status == StatusActive
}
